[package]
name = "counters"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { path = "../../leptos" }
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
