[package]
name = "leptos_router"
version = "0.1.0-beta"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Router for the Leptos web framework."

[dependencies]
leptos.workspace = true
cfg-if = "1"
common_macros = "0.1"
gloo-net = "0.2"
itertools = "0.10"
lazy_static = "1"
linear-map = "1"
log = "0.4"
regex = { version = "1", optional = true }
bincode = "1"
url = { version = "2", optional = true }
urlencoding = "2"
thiserror = "1"
serde_urlencoded = "0.7"
serde = "1"
js-sys = { version = "0.3" }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dependencies.web-sys]
version = "0.3"
features = [
	# History/Routing
	"History",
	"HtmlAnchorElement",
	"MouseEvent",
	"Url",
	# Form
	"FormData",
	"HtmlButtonElement",
	"HtmlFormElement",
	"HtmlInputElement",
	"SubmitEvent",
	"Url",
	"UrlSearchParams",
	# Fetching in Hydrate Mode
	"Headers",
	"Request",
	"RequestInit",
	"RequestMode",
	"Response",
	"Window",
]

[features]
default = []
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "dep:url", "dep:regex"]
stable = ["leptos/stable"]

[package.metadata.cargo-all-features]
# No need to test optional dependencies as they are enabled by the ssr feature
denylist = ["url", "regex", "stable"]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]
